name: Node.js CI

# Cancela ejecuciones anteriores si hay nuevos cambios en la misma rama
concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project (si existe script build)
        run: npm run build --if-present

  test:
    runs-on: ubuntu-22
    needs: build
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
